language: objective-c
osx_image: xcode8
script:
- xcodebuild clean build -workspace Examples/SKAsyncGLViewController/SKAsyncGLViewController.xcworkspace -scheme SKAsyncGLViewController -sdk iphonesimulator
